/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;


public class App {

    public String a = "a";
    public String b = "b";
    public boolean c = false;

    public void aa()
    {
        var a = 1;
        Object b = 2;
        System.out.println("HEREEEE::" + a);
        var data = new java.util.HashMap<String, Object>() {{
            put( "1", 1 );
            put( "2", 2 );
        }};
        var lista = new java.util.ArrayList<Object>(java.util.Arrays.asList(1, 3, 4, "5"));
        Helpers.GetValue(data, "1");
        Aux.fix();
        // System.out.println(a);
        // System.out.println(data["1"]);
        // System.out.println(lista[2]);
        // for (var i = 0; isLessThan(i, getArrayLength(lista)); i++)
        // {
        //     System.out.println(lista[i]);
        // }
    }

    public void test() {
        System.out.println("test");
    }

    public String getGreeting() {
        var i = 1;
        i += 1;
        var a = "aaa";
        a += "bbb";
        // var c = new HashMap<String, String>();
        return "Hello World222!" + String.valueOf(i) + a;
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        // var app = new App();
        // System.out.println(app.getGreeting());
        // app.test();
        // app.aa();
        // for (var i = 0; i < 5; ((int) i)++) {
        //     System.out.println("i: " + i);
        // }
    }
}
